const LAT_VALIDATION = {
  MIN: -90,
  MAX: 90,
};

const LNG_VALIDATION = {
  MIN: -180,
  MAX: 180,
};

const COORDINATES_VALIDATION = {
  LAT: LAT_VALIDATION,
  LNG: LNG_VALIDATION,
};

const HOUR_VALIDATION = {
  MIN: 0,
  MAX: 23,
};

const MINUTE_VALIDATION = {
  MIN: 0,
  MAX: 59,
};

const TIME_OF_DAY_VALIDATION = {
  HOUR: HOUR_VALIDATION,
  MINUTE: MINUTE_VALIDATION,
};

export { COORDINATES_VALIDATION, LAT_VALIDATION, LNG_VALIDATION, TIME_OF_DAY_VALIDATION, HOUR_VALIDATION, MINUTE_VALIDATION };
