const ACCOUNT_VALIDATION = {
  MIN_LENGTH: 4,
  MAX_LENGTH: 32,
  PATTERN: /^[a-zA-Z0-9_]+$/,
  PATTERN_MESSAGE: "帳號只能有英文、數字、底線",
};

const PASSWORD_VALIDATION = {
  MIN_LENGTH: 6,
  MAX_LENGTH: 32,
  PATTERN: /^[a-zA-Z0-9_]+$/,
  PATTERN_MESSAGE: "密碼只能有英文、數字、底線",
};

const NICKNAME_VALIDATION = {
  MIN_LENGTH: 2,
  MAX_LENGTH: 16,
};

const REGISTER_REQUSER_VALIDATION = {
  ACCOUNT: ACCOUNT_VALIDATION,
  PASSWORD: PASSWORD_VALIDATION,
  NICKNAME: NICKNAME_VALIDATION,
};

const LOGIN_REQUSER_VALIDATION = {
  ACCOUNT: ACCOUNT_VALIDATION,
  PASSWORD: PASSWORD_VALIDATION,
};

const ACCOUNTSETTING_REQUSER_VALIDATION = {
  ACCOUNT: ACCOUNT_VALIDATION,
  PASSWORD: PASSWORD_VALIDATION,
};

export { REGISTER_REQUSER_VALIDATION, LOGIN_REQUSER_VALIDATION, ACCOUNTSETTING_REQUSER_VALIDATION };
