const ACCOUNT_VALIDATION = {
  MIN_LENGTH: 4,
  MAX_LENGTH: 32,
  PATTERN: /^[a-zA-Z0-9_]+$/,
};

const PASSWORD_VALIDATION = {
  MIN_LENGTH: 6,
  MAX_LENGTH: 32,
  PATTERN: /^[a-zA-Z0-9_]+$/,
};

const EMAIL_VALIDATION = {
  MIN_LENGTH: 0,
  MAX_LENGTH: 100,
  PATTERN: /^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/i,
};

const USER_VALIDATION = {
  ACCOUNT: ACCOUNT_VALIDATION,
  PASSWORD: PASSWORD_VALIDATION,
  EMAIL: EMAIL_VALIDATION,
};

export { USER_VALIDATION };
